# Generated by Django 4.1.2 on 2022-10-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tcc', '0002_tcc_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcc',
            name='arquivo',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
