# Generated by Django 4.1.2 on 2022-10-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tcc', '0005_alter_tcc_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcc',
            name='arquivo',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
    ]
